<?php
return[
    'items'=>[
        'Dashboard'=>[],
        'Category'=>[],
        'Rolepermission'=>[],
        'Courses'=>[],
        'Users'=>[],
        'UsersProfile'=>[],
        'payments'=>[]
        ]
];
